program: gnn_fiedler_approx/algebraic_connectivity_script.py
name: batchsize_sweep
method: bayes  # Bayesian works for small number of continuous parameters.
metric:
  goal: minimize
  name: val_loss
parameters:
  architecture:
    value: GraphSAGE
  hidden_channels:
    value: 32
  gnn_layers:
    value: 5
  mlp_layers:
    value: 2
  dropout:
    value: 0.0
  activation:
    value: tanh
  pool:
    value: softmax
  jk:
    value: cat
  optimizer:
    value: adam
  learning_rate:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.1
  batch_size:
    values: [1, 2, 4, 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384]
  epochs:
    value: 1500
  # model_kwargs:
  #   parameters:
  #     aggregators:
  #       value: [min, max, mean, std]
  #     scalers:
  #       value: [identity, amplification, attenuation]
  selected_features:
    values:
      - [degree, degree_centrality, core_number, triangles, clustering, close_centrality]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--eval-type"
  - "basic"
  - "--eval-target"
  - "best"


