program: algebraic_connectivity_script.py
name: graphsage
method: grid  # Bayesian works for small number of continuous parameters.
metric:
  goal: minimize
  name: test_loss
parameters:
  architecture:
    values: [GraphSAGE]
  hidden_channels:
    values: [32]
  gnn_layers:
    values: [5]
  mlp_layers:
    value: 1
  dropout:
    value: 0.0
  activation:
    values: [tanh]
  pool:
    values: [max]
  optimizer:
    value: adam
  learning_rate:
    values: [0.01]
  epochs:
    value: 1000
  jk:
    values: ["none"]
  model_kwargs:
    parameters:
      aggr:
        values: ["lstm", "mean", "max"]
      project:
        values: [True, False]
      root_weight:
        values: [True, False]


command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--eval-type"
  - "basic"
  - "--eval-target"
  - "best"


