program: algebraic_connectivity_script.py
name: dumb_baselines
method: grid  # Bayesian works for small number of continuous parameters.
metric:
  goal: minimize
  name: test_loss
parameters:
  architecture:
    values: [GraphSAGE, MLP]
  hidden_channels:
    values: [32]
  gnn_layers:
    values: [5]
  dropout:
    values: [0.0]
  activation:
    values: [tanh]
  aggr:
    values: [add]
  optimizer:
    value: adam
  learning_rate:
    values: [0.01]
  epochs:
    value: 1000
  selected_features:
    values:
      - [zero]
      - [ones]
      - [random1]
      - [random1, random2]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--eval-type"
  - "detailed"
  - "--eval-target"
  - "best"


