program: gnn_fiedler_approx/algebraic_connectivity_script.py
name: normalization
method: grid  # Bayesian works for small number of continuous parameters.
metric:
  goal: minimize
  name: test_loss
parameters:
  architecture:
    values: [GraphSAGE]
  hidden_channels:
    values: [32]
  gnn_layers:
    values: [5]
  mlp_layers:
    value: 2
  dropout:
    value: 0.0
  activation:
    values: [tanh]
  pool:
    values: [s2s, softmax, multi++, max]
  optimizer:
    value: adam
  learning_rate:
    values: [0.01]
  epochs:
    value: 5000
  jk:
    values: [cat]
  # model_kwargs:
  #   parameters:
  #     aggregators:
  #       value: [min, max, mean, std]
  #     scalers:
  #       value: [identity, amplification, attenuation]
  label_normalization:
    values: [null, z-score, boxcox]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--eval-type"
  - "basic"
  - "--eval-target"
  - "best"


