program: gnn_fiedler_approx/algebraic_connectivity_script.py
name: pooling_functions
method: grid  # Bayesian works for small number of continuous parameters.
metric:
  goal: minimize
  name: test_loss
parameters:
  architecture:
    values: [GraphSAGE, GIN]
  hidden_channels:
    values: [32]
  gnn_layers:
    values: [5]
  mlp_layers:
    value: 2
  dropout:
    value: 0.0
  activation:
    values: [tanh, relu]
  pool:
    values: [median, min, s2s, multi]
  optimizer:
    value: adam
  learning_rate:
    values: [0.01, 0.001]
  epochs:
    value: 2000
  jk:
    values: ["cat"]


command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--eval-type"
  - "basic"
  - "--eval-target"
  - "best"


