program: gnn_fiedler_approx/algebraic_connectivity_script.py
name: ffn
method: grid  # Bayesian works for small number of continuous parameters.
metric:
  goal: minimize
  name: val_loss
parameters:
## Model configuration
  architecture:
    values: [GCN, GIN, GraphSAGE, GCN+, GIN+, GraphSAGE+]
  hidden_channels:
    value: 32
  gnn_layers:
    value: 5
  mlp_layers:
    value: 2
  dropout:
    value: 0.05
  activation:
    values: [tanh, relu]
  pool:
    value: softmax
  norm:
    values: [null, batch, graph]
  jk:
    values: [cat, none]
  model_kwargs:
    parameters:
      pre_scaler:
        value: true
      residual:
        value: true
      ffn:
        values: [true, false]
## Training configuration
  optimizer:
    value: adam
  learning_rate:
    value: 0.001
  batch_size:
    value: "100%"
  epochs:
    value: 100_000
## Dataset configuration
  selected_features:
    values:
      - [degree, degree_centrality, core_number, triangles, clustering, close_centrality]
  transform:
    value: null

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--eval-type"
  - "basic"
  - "--eval-target"
  - "best"