program: algebraic_connectivity_script.py
name: jumping_knowledge
method: grid  # Bayesian works for small number of continuous parameters.
metric:
  goal: minimize
  name: test_loss
parameters:
  architecture:
    values: [GCN, GIN, GraphSAGE]
  hidden_channels:
    values: [32]
  gnn_layers:
    values: [5]
  mlp_layers:
    value: 1
  dropout:
    value: 0.0
  activation:
    values: [relu, tanh]
  pool:
    values: [add, max]
  optimizer:
    value: adam
  learning_rate:
    values: [0.01]
  epochs:
    value: 2000
  jk:
    values: [null, "last", "cat", "max"]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--eval-type"
  - "basic"
  - "--eval-target"
  - "best"


