program: algebraic_connectivity_script.py
name: full_first_sweep
method: grid
metric:
  goal: minimize
  name: test_loss
parameters:
  architecture:
    values: [GCN, GraphSAGE, GIN, GAT]
  hidden_channels:
    values: [8, 16, 32, 64]
  num_layers:
    values: [1, 2, 3, 5]
  optimizer:
    value: adam
  learning_rate:
    values: [0.1, 0.01, 0.001]
  epochs:
    value: 1000
early_terminate:
  type: hyperband
  eta: 3
  min_iter: 300
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config"
  - "config/full_sweep.yaml"