program: algebraic_connectivity_script.py
name: full_sweep_v2
method: grid  # Bayesian works for small number of continuous parameters.
metric:
  goal: minimize
  name: test_loss
parameters:
  architecture:
    values: [GCN, GraphSAGE, GIN, GAT]
  hidden_channels:
    values: [16, 32, 64, 128]
  num_layers:
    values: [1, 3, 5, 10]
  dropout:
    values: [0.0, 0.5]
  activation:
    values: [relu, tanh]
  aggr:
    values: [mean, add, max]
  optimizer:
    value: adam
  learning_rate:
    values: [0.01, 0.001]
  epochs:
    value: 1000
early_terminate:
  type: hyperband
  eta: 3
  min_iter: 300
command:
  - ${env}
  - ${interpreter}
  - ${program}
