program: algebraic_connectivity_script.py
name: new_feature_sweep
method: grid  # Bayesian works for small number of continuous parameters.
metric:
  goal: minimize
  name: test_loss
parameters:
  architecture:
    values: [GCN, GraphSAGE, GIN, GAT]
  hidden_channels:
    values: [32, 64, 128]
  num_layers:
    values: [3, 5, 10]
  dropout:
    values: [0.0]
  activation:
    values: [relu, tanh]
  aggr:
    values: [mean, max]
  optimizer:
    value: adam
  learning_rate:
    values: [0.01]
  epochs:
    value: 1000
early_terminate:
  type: hyperband
  eta: 3
  min_iter: 300
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--evaluation"
  - "basic"
