program: algebraic_connectivity_script.py
name: test_sweep
method: grid
metric:
  goal: minimize
  name: test_loss
parameters:
  architecture:
    values: [GCN, GAT]
  hidden_channels:
    values: [16]
  num_layers:
    values: [3]
  optimizer:
    value: adam
  learning_rate:
    values: [0.01]
  epochs:
    value: 1000
early_terminate:
  type: hyperband
  eta: 3
  min_iter: 300
command:
  - ${env}
  - ${interpreter}
  - ${program}